version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: test-mysql1
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3307:3306
    volumes:
      - /home/vagrant/mydata/mysql/data:/var/lib/mysql #数据文件目录挂载
      - /home/vagrant/mydata/mysql/conf:/etc/mysql #配置文件目录挂载
      - /home/vagrant/mydata/mysql/log:/var/log/mysql #日志文件目录挂载